In [1]:
import numpy as np

In [2]:
?numpy

Object `numpy` not found.


In [3]:
np?

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([2.333,90,44,4.55])

array([ 2.333, 90.   , 44.   ,  4.55 ])

In [7]:
%%timeit
l1 = list(range(5000000))
l2 = list(range(5000000))


270 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%%timeit
np_array_1 = np.arange(5000000)
np_array_2 = np.arange(5000000)


23.8 ms ± 4.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
a = np.array([1,2,3,4,5])

In [18]:
a[1:4:2]

array([2, 4])

In [19]:
a[0]

1

In [21]:
a[1:3:2]

array([2])